

#random.seed 1234567890
simulation.cycles 1

network.size 100
NR_DC 10
NR_NODE_PER_DC 100

protocol.link IdleProtocol

protocol.coord RenaterNode

init.0 RenaterInitializer
init.0.protocol coord
init.0.nr_dc NR_DC
init.0.nr_node_per_dc NR_NODE_PER_DC
#init.0.dc_file configs/renaternodes.txt

init.1 WireRenater
init.1.protocol link
init.1.coord_protocol coord

#init.1 WireScaleFreeBA
#init.1.protocol link
#init.1.k 2

#init.1 example.hot.WireInetTopology
#init.1.protocol link #the linkable to be wired
#init.1.coord_protocol coord
#init.1.alpha 4

control.io example.hot.InetObserver
control.io.protocol link
control.io.coord_protocol coord
control.io.file_base out/graph

control.degree DegreeStats
control.degree.protocol link
control.degree.undir
control.degree.method freq

include.control io #degree